### ISSUE TITLE
Option for verbose upload

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-ci-setup-feedstock#215]
Currently we silence uploads

https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/7279d604aa0a9949e2c7fae15a3949847743aaa1/recipe/conda_forge_ci_setup/upload_or_check_non_existence.py#L103-L106

However if we run into an issue where the uploading itself is broken and we would like to debug it ( like issue https://github.com/conda-forge/kubo-feedstock/issues/5 ), currently we lack the ability to configure a verbose upload. Would be good to have some way to configure this

**Comment by mbargull** [comment]
Thanks for raising the issue.
We might be able to add `--show-traceback` to see additional error information without increasing the verbosity otherwise.
We probably wouldn't have to introduce an option for that.

**Comment by jakirkham** [comment]
Yep tried this locally and it seems to work

```sh
$  anaconda --quiet --show-traceback upload -u jakirkham -l test ~/Downloads/kubo-feedstock_conda_artifacts_20221130/win-64/kubo-0.17.0-h07f9b4e_0.conda    
```

```python   
[ERROR] 
Traceback (most recent call last):
  File "/Users/jkirkham/miniforge/bin/anaconda", line 10, in <module>
    sys.exit(main())
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 158, in main
    binstar_main(command_module, args, exit,
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 138, in binstar_main
    return args.main(args)
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 315, in main
    package_info = upload_package(
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 243, in upload_package
    upload_info = aserver_api.upload(username, package_name, version, file_attrs['basename'], fd,
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/__init__.py", line 572, in upload
    self._check_response(res)
  File "/Users/jkirkham/miniforge/lib/python3.10/site-packages/binstar_client/__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Conflict: ('file win-64/kubo-0.17.0-h07f9b4e_0.conda already exists for package kubo version 0.17.0', 409)
```

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/219 ) to add this flag
