### ISSUE TITLE
The 2.0 branch is having issues uploading sometimes

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-forge-ci-setup-feedstock#22]
I am seeing the following issue on the make feedstock, with some uploads: https://travis-ci.org/conda-forge/make-feedstock/jobs/418844902#L984  

Not really sure what is going on here :( CC @mariusvniekerk 

```
$ upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_c_compilertoolchain_c.yaml
Attempting to finalize metadata for make
Solving environment: ...working... done
Solving environment: ...working... done
[ERROR] File "/Users/travis/miniconda3/conda-bld/osx-64/make-4.2.1-h470a237_1002.tar.bz2" does not exist
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_forge_ci_setup/build_utils.py", line 81, in upload_package
    upload_or_check(recipe_root, owner, channel, [config_file])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 123, in upload_or_check
    upload(token_fn, path, owner, channel)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 65, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmpx90qiwh6/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/make-4.2.1-h470a237_1002.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

**Comment by mariusvniekerk** [comment]
this is related to #26 nd #27 which should fix this.  This is a build number clobber issue
