### ISSUE TITLE
Release of `urllib3` v2 breaks `binstar_client` from `anaconda-client`

### ISSUE THREAD

**Issue by peterbygrave** [conda-forge/conda-forge-ci-setup-feedstock#242]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi,

There is an issue with dependency of this package leading to this error:

```
conda create -n conda-forge-ci-setup-env conda-forge-ci-setup
conda activate conda-forge-ci-setup-env
python -c "from conda_forge_ci_setup import build_utils"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/peter/miniconda3/envs/conda-forge-ci-setup-env/lib/python3.11/site-packages/conda_forge_ci_setup/build_utils.py", line 15, in <module>
    from conda_forge_ci_setup.upload_or_check_non_existence import retry_upload_or_check
  File "/Users/peter/miniconda3/envs/conda-forge-ci-setup-env/lib/python3.11/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 12, in <module>
    from binstar_client.utils import get_server_api
  File "/Users/peter/miniconda3/envs/conda-forge-ci-setup-env/lib/python3.11/site-packages/binstar_client/__init__.py", line 26, in <module>
    from .requests_ext import NullAuth
  File "/Users/peter/miniconda3/envs/conda-forge-ci-setup-env/lib/python3.11/site-packages/binstar_client/requests_ext.py", line 11, in <module>
    from urllib3.filepost import choose_boundary, iter_fields
ImportError: cannot import name 'iter_fields' from 'urllib3.filepost' (/Users/peter/miniconda3/envs/conda-forge-ci-setup-env/lib/python3.11/site-packages/urllib3/filepost.py)
```

This is more of an FYI as this is not really a direct issue with this package, but you might consider pinning `urllib3 <2`. I think the most upstream issue I can find is https://github.com/Anaconda-Platform/anaconda-client/issues/654.

Hope this helps, even if just an early warning.

### Installed packages

```shell
conda-forge-ci-setup
```

### Environment info

```shell
active environment : conda-forge-ci-setup-env
    active env location : /Users/peter/miniconda3/envs/conda-forge-ci-setup-env
            shell level : 2
       user config file : /Users/peter/.condarc
 populated config files : /Users/peter/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.2.1=0
                          __unix=0=0
       base environment : /Users/peter/miniconda3  (writable)
      conda av data dir : /Users/peter/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/peter/miniconda3/pkgs
                          /Users/peter/.conda/pkgs
       envs directories : /Users/peter/miniconda3/envs
                          /Users/peter/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.10 Darwin/22.3.0 OSX/13.2.1 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.4.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jaimergp** [comment]
I think we can close here now but leave https://github.com/conda-forge/anaconda-client-feedstock/issues/40 open.

Thoughts @peterbygrave?

**Comment by peterbygrave** [comment]
Yep happy to close as being dealt with elsewhere
