### ISSUE TITLE
Appveyor build failing with [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by brian-rose** [conda-forge/conda-forge-ci-setup-feedstock#43]
Issue:

Trying to update climlab-feedstock (conda-forge/climlab-feedstock#19)  and [this build on Appveyor](https://ci.appveyor.com/project/conda-forge/climlab-feedstock/builds/21834586/job/95hxwx538cu8qoov) is failing with
```
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
```

Traceback shows this is triggered by a `urllib2` call in [ff_ci_pr_build.py](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py).

The Appveyor build is working for Python 3.7 but not for Python 3.6

If there's a better place to open this, please let me know, thanks!

Full error message below.

```
Checking to see if this PR build is outdated.
9Traceback (most recent call last):
10  File "C:\projects\climlab-feedstock\ff_ci_pr_build.py", line 201, in <module>
11    sys.exit(main())
12  File "C:\projects\climlab-feedstock\ff_ci_pr_build.py", line 192, in main
13    exit_code = int(appveyor_check_latest_pr_build(repo, pr, bld) is False)
14  File "C:\projects\climlab-feedstock\ff_ci_pr_build.py", line 117, in appveyor_check_latest_pr_build
15    data = request_json(url.format(repo=repo, total_builds=total_builds), headers=headers)
16  File "C:\projects\climlab-feedstock\ff_ci_pr_build.py", line 46, in request_json
17    with contextlib.closing(urlopen(request)) as response:
18  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
19    return opener.open(url, data, timeout)
20  File "C:\Python27\lib\urllib2.py", line 429, in open
21    response = self._open(req, data)
22  File "C:\Python27\lib\urllib2.py", line 447, in _open
23    '_open', req)
24  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
25    result = func(*args)
26  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
27    context=self._context)
28  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
29    raise URLError(err)
30urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
31Command exited with code 1
```

**Comment by isuruf** [comment]
That's a network issue. Restarting should fix it
